apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinpet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinpet
  template:
    metadata:
      labels:
        app: coinpet
    spec:
      containers:
        - name: coinpet
          image: gcr.io/verdant-catcher-269008/coinpet-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/coinpet
          imagePullPolicy: Always
