apiVersion: v1
kind: Service
metadata:
  name: coinpet
spec:
  selector:
    app: coinpet
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinpet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinpet
  template:
    metadata:
      labels:
        app: coinpet
    spec:
      containers:
        - name: coinpet
          image: nonownonow/coinpet:1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
