apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinpet-db
spec:
  selector:
    matchLabels:
      app: coinpet-db
  template:
    metadata:
      labels:
        app: coinpet-db
    spec:
      containers:
        - name: coinpet-db
          image: gcr.io/verdant-catcher-269008/helloworld-gke:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
